import { useState } from 'react';
import { useI18n } from '../i18n';
import type { OnlineDataset } from '../types/activity';
import { formatDate } from '../utils/activity';
import ActivityHeatmap from './ActivityHeatmap';
import { Sparkline, TrainingTrend } from './Charts';
export default function OnlineProfile({ dataset, players }: { dataset: OnlineDataset; players: { id: string; displayName: string }[] }) {
  const { t, language, locale, setLanguage, weekdays } = useI18n();
  const isLocal = dataset.history?.source === 'local-stats';
  const onlineCheckedAt = dataset.scoreTracking.fetchedAt;
  const historyLabel = isLocal ? onlineCheckedAt ? 'hybridHistory' : 'localHistory' : 'partialHistory';
  const pollingLate = onlineCheckedAt && Date.now() - Date.parse(onlineCheckedAt) > 30 * 60000;
  const [year, setYear] = useState(Number(dataset.today.slice(0, 4)));
  const currentYear = Number(dataset.today.slice(0, 4));
  const years = [...new Set([currentYear, currentYear - 1, ...dataset.daily.map(day => Number(day.date.slice(0, 4)))])].sort((a, b) => b - a);
  const data = dataset.daily.filter(day => day.date.startsWith(String(year)));
  const active = data.filter(day => day.runs > 0).length;
  const yearRuns = data.reduce((sum, day) => sum + day.runs, 0);
  const number = new Intl.NumberFormat(locale);
  const datetime = (instant: string) => new Date(instant).toLocaleString(locale, { timeZone: dataset.profile.timezone, year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  const subtitle = dataset.trackingSince ? t('trackingSince', { date: datetime(dataset.trackingSince) }) : t('waitingBaseline');
  return <main className="profile-page">
    <header className="profile-header"><div className="identity"><div className="eyebrow">{t('eyebrow')}</div><h1>{dataset.profile.displayName}<span className="profile-dot" /></h1><p className="site-title">{t('title')}</p><p className="description">{t('description')}</p></div><div className="header-controls">
      <span className="demo-badge"><i />{t(dataset.history ? historyLabel : 'online')}</span>
      {players.length > 1 && <label className="year-select"><span>{t('player')}</span><select aria-label={t('player')} value={dataset.profile.id} onChange={event => { const url = new URL(location.href); url.searchParams.set('player', event.target.value); location.assign(url); }}>{players.map(player => <option key={player.id} value={player.id}>{player.displayName}</option>)}</select></label>}
      <label className="year-select"><span>{t('calendarYear')}</span><select value={year} onChange={event => setYear(Number(event.target.value))} aria-label={t('activityYear')}>{years.map(value => <option key={value}>{value}</option>)}</select></label>
      <label className="year-select language-select"><span>{t('language')}</span><select value={language} onChange={event => setLanguage(event.target.value as 'en' | 'zh')} aria-label={t('language')}><option value="en">English</option><option value="zh">中文</option></select></label>
    </div></header>
    <div className="summary" aria-label={t('summary')}><div><strong>{data.length ? active : '—'}</strong><span>{t('knownActive')} · {year}</span></div><div><strong className="teal">{data.length ? number.format(yearRuns) : '—'}</strong><span>{t('recordedRuns')} · {year}</span></div><div><strong className="warm">{dataset.trackingSince ? number.format(dataset.sampledPlays) : '—'}</strong><span>{t('observedPlays')}</span></div><div><strong className="lilac">—</strong><span>{t('training')}</span></div></div>
    <div className="data-notice"><p>{isLocal && dataset.history?.firstDate ? `${formatDate(dataset.history.firstDate, locale)} – ${formatDate(dataset.history.lastDate!, locale)}` : subtitle} · {dataset.profile.timezone}</p><p>{dataset.history ? t(isLocal ? dataset.history.onlineAdded ? 'hybridNotice' : 'localNotice' : 'historyNotice', { count: dataset.history.recordCount, scenarios: dataset.history.scenarioCount }) : t('onlineNotice')}</p>{dataset.scoreTracking.fetchedAt && <p>{t('pollingUpdated', { date: datetime(dataset.scoreTracking.fetchedAt) })}</p>}{pollingLate && <p>{t('pollingLate')}</p>}{dataset.scoreTracking.possibleGaps > 0 && <p>{t('pollingGap', { count: dataset.scoreTracking.possibleGaps })}</p>}{dataset.scoreTracking.failedScenarios > 0 && <p>{t('pollingFailed', { count: dataset.scoreTracking.failedScenarios })}</p>}{!isLocal && <p>{t('counterUnverified')}</p>}{dataset.unassignedPlays > 0 && <p>{t('crossDay', { count: dataset.unassignedPlays })}</p>}{dataset.counterResets > 0 && <p>{t('resets')}</p>}</div>
    <section className="panel activity-panel"><div className="section-heading"><div><h2>{t('activity')}</h2><p>{t(dataset.history ? historyLabel : 'observedPlays')} · {t('dailyTotal')}</p></div><span className="metric-label">{t('yearRuns', { year, count: number.format(yearRuns) })}</span></div><ActivityHeatmap data={data} year={year} metric="runs" today={dataset.today}/></section>
    <div className="module-grid"><section className="panel"><div className="section-heading"><div><h2>{t('trend')}</h2><p>{t(dataset.history ? 'historyTrend' : 'sampleTrend')}</p></div><span className="metric-label">{t('yearRuns', { year, count: number.format(yearRuns) })}</span></div><TrainingTrend data={data} metric="runs" year={year} through={dataset.today}/><p className="empty-note">{t('weeklyExplanation')}</p></section>
      <section className="panel focus-panel"><div className="section-heading"><div><h2>{t('focus')}</h2><p>{t('historyFocus')}</p></div></div><div className="scenario-list">{dataset.focus.length ? dataset.focus.map((scenario, index) => <div className={`scenario-row accent-${index}`} key={scenario.id}><div className="scenario-meta"><span>{scenario.scenarioName}</span><strong>{number.format(scenario.runs)} <small>{t('runs')}</small></strong></div><div className="scenario-bottom"><div className="bar-track"><div style={{ width: `${scenario.runs / dataset.focus[0].runs * 100}%` }}/></div></div></div>) : <p className="empty-note">{t('focusWaiting')}</p>}</div></section>
      <section className="panel progress-panel"><div className="section-heading"><div><h2>{t('progress')}</h2><p>{t('historyProgress')}</p></div></div>{dataset.scoreProgress.length ? <div className="progress-list">{dataset.scoreProgress.map(scenario => {
        const values = scenario.scores.map(row => row.score);
        const latest = values.at(-1)!;
        const change = values[0] > 0 ? (latest / values[0] - 1) * 100 : null;
        return <div className="progress-row" key={scenario.id}><span className="scenario-name">{scenario.scenarioName}</span><strong>{number.format(latest)}</strong><span className={change !== null && change < 0 ? 'decline' : 'gain'} title={t('historyPercent')}>{change === null ? '—' : `${change >= 0 ? '+' : ''}${change.toLocaleString(locale, { maximumFractionDigits: 1 })}%`}</span><Sparkline values={values} name={scenario.scenarioName}/></div>;
      })}</div> : dataset.pbEvents.length ? <div>{dataset.pbEvents.map(event => <div className="pb-row" key={`${event.timestamp}:${event.scenarioId}`}><span>{event.scenarioName}<small>{datetime(event.timestamp)}</small></span><strong className="teal">{number.format(event.score)}</strong></div>)}</div> : <p className="empty-note">{t('noScores')}</p>}</section>
      <section className="panel pattern-panel"><div className="section-heading"><div><h2>{t('pattern')}</h2><p>{t('historyFocus')}</p></div></div>{dataset.pattern ? <><div className="pattern-stats"><div><strong className="teal">{dataset.pattern.activeDays}</strong><span>{t('recordedActive30')}</span></div><div><strong>{number.format(Math.round(dataset.pattern.runs / dataset.pattern.activeDays))}</strong><span>{t('runsActive')}</span></div><div><span>{t('recordedPeak')}</span><strong className="warm peak">{dataset.pattern.peakStart === null ? '—' : `${String(dataset.pattern.peakStart).padStart(2, '0')}:00–${String(dataset.pattern.peakEnd).padStart(2, '0')}:00`}</strong><span className="tiny">{dataset.profile.timezone}</span></div></div><div className="weekday-chart" role="img" aria-label={t('recordedWeekday')}>{weekdays.map((day, index) => <div key={day}><div className="weekday-bar-space"><span style={{ height: `${dataset.pattern!.weekdayRuns[index] / Math.max(...dataset.pattern!.weekdayRuns, 1) * 100}%` }} title={`${day}: ${dataset.pattern!.weekdayRuns[index]} ${t('runs')}`}/></div><span>{day}</span></div>)}</div></> : <p className="empty-note">{t('noPattern')}</p>}</section>
    </div>
    <footer><span>{onlineCheckedAt ? t('pollingUpdated', { date: datetime(onlineCheckedAt) }) : dataset.history ? t(isLocal ? 'localFetched' : 'historyFetched', { date: datetime(dataset.history.fetchedAt) }) : dataset.updatedAt ? t('updated', { date: datetime(dataset.updatedAt) }) : subtitle}</span><span><a href="?demo=1">{t('demoLink')}</a> <span className="footer-divider">/</span> KovaaK Activity</span></footer>
    <span className="sr-only">{formatDate(dataset.today, locale)}</span>
  </main>;
}
