import { createContext, useContext, useEffect, useState } from 'react';
import type { ReactNode } from 'react';
export type Language = 'en' | 'zh';
const en = {
  weeklyTotal: 'Weekly total', dailyTotal: 'Daily count', yearRuns: '{year} total · {count} runs', weeklyExplanation: 'Each point totals Monday–Sunday from the same daily records as the heatmap.',
  pollingUpdated: 'Online scores checked {date}', pollingGap: '{count} polling windows may have missing runs. History remains incomplete.', pollingFailed: '{count} scenarios could not be refreshed; previous scores are preserved.', hybridNotice: 'Saved {count} training records across {scenarios} scenarios from local Stats and deduplicated online scores. Missing files or truncated API windows may leave gaps. Duration remains unavailable.',
  localHistory: 'Local Stats history', localNotice: 'Imported {count} completed-run CSVs across {scenarios} scenarios. Counts cover surviving local files; deleted files, unsaved runs and time outside challenges are not included. Duration is not inferred from Fight Time.', localFetched: 'Local Stats imported {date}', recordedRuns: 'Recorded Runs', recordedActive30: 'recorded active days / 30 days', runsActive: 'runs / recorded active day', recordedPeak: 'Most recorded run starts', recordedWeekday: 'Recorded runs by weekday · last 30 days',
  partialHistory: 'Partial online history', historyRecords: 'Score Records', historyNotice: 'Recovered {count} timestamped scores across {scenarios} scenarios. Each scenario has limited history. Daily counts are lower bounds; unrecorded days remain unknown. Duration is unavailable.', historyFetched: 'History retrieved {date}', historyTrend: 'Weekly confirmed runs · partial history', historyFocus: 'Last 30 days · confirmed records', historyProgress: 'Last 30 days · latest score vs first available score', historyPercent: 'Change between available scores, not PB improvement', counterUnverified: 'The reported cumulative Plays counter is being verified and is not used as a lifetime total.',
  online: 'Online tracking', reportedPlays: 'Reported Plays', observedPlays: 'Sampled Plays', knownActive: 'Known Active Days', durationMissing: 'Duration unavailable', trackingSince: 'Tracking since {date}', waitingBaseline: 'Waiting for the first snapshot', updated: 'Updated {date}', onlineNotice: 'Activity uses changes in KovaaK-reported Plays, not a complete run log. Daily cells show sampled lower bounds; missing history stays unknown. Training time is unavailable.', focusWaiting: 'Recent scenario focus will appear after comparable snapshots record new Plays.', pbSubtitle: 'Latest reported PB events · not full score history', pbWaiting: 'No public PB events available.', progressMissing: 'Improvement percentages require score history and are not available yet.', patternWaiting: 'Training duration and peak hours cannot be determined from these counters.', crossDay: '{count} sampled Plays cross a day boundary and are excluded from daily cells.', sampleTrend: 'Sampled weekly Plays · incomplete daily coverage', loadError: 'Unable to load player data. Retry or check the static data files.', retry: 'Retry', loading: 'Loading profile…', player: 'Player', demoLink: 'View demo', partial: 'Incomplete coverage · lower bound', zeroPartial: 'No increase during sampled intervals; full-day activity unknown', resets: 'A counter reset was detected; affected intervals are excluded.', liveLink: 'View tracked profile', knownDays: '{count} known active days · partial records', dataUnavailable: 'Unavailable',
  language: 'Language', eyebrow: 'THE PRACTICE BEHIND THE PROGRESS', title: 'KovaaK Training Activity', description: 'Practice consistency and progression overview', demo: 'Demo profile', calendarYear: 'Calendar year', activityYear: 'Activity year', summary: 'Training summary', activeDays: 'Active Days', training: 'Training', currentStreak: 'Current Streak', yearEndStreak: 'Year-end Streak', runs: 'runs', runsLabel: 'Runs', hour: 'h', minute: 'min', minutes: 'minutes',
  activity: 'Training Activity', activitySubtitle: 'Every session adds up. Your {year} in practice.', metric: 'Heatmap metric', time: 'Time', noActivity: 'No activity recorded for {year}. Unknown history is shown separately from zero training.', trend: 'Training Trend', weeklyTime: 'Weekly training time', weeklyRuns: 'Weekly training runs', focus: 'Scenario Focus', last30: 'Last 30 tracked days', noScenarios: 'No scenario activity available.', progress: 'Recent Progress', progressSubtitle: 'Personal best progression · last 30 tracked days', noScores: 'No score history available.', pattern: 'Current Pattern', daysWeek: 'days / week', perActive: '/ active day', peak: 'Peak time', illustrative: 'Illustrative', weekdayChart: 'Training minutes by weekday, last 30 tracked days', noPattern: 'Training patterns will appear as activity accumulates.', footer: 'Built through practice.', mock: 'Illustrative mock data', asOf: 'As of {date}',
  futureDate: 'Future date', noData: 'No data', intensity: 'Activity intensity', future: 'Future', activePercent: '{count} active days · {percent}% of elapsed days', noDays: 'No recorded days', noHistory: 'No historical data', timeUnavailable: 'Time unavailable', newPBs: 'new PBs', scenarios: 'scenarios', noTrend: 'No training data for this year', weeklyHours: 'Weekly training hours', weekOf: 'Week of {date}', hours: 'hours', scoreRange: '{name}: {first} to {last}',
};
const zh: Record<keyof typeof en, string> = {
  weeklyTotal: '本周合计', dailyTotal: '当天次数', yearRuns: '{year} 年合计 · {count} 次', weeklyExplanation: '每个点为周一至周日合计，使用与热力图相同的每日记录。',
  pollingUpdated: '线上成绩检查于 {date}', pollingGap: '有 {count} 次抓取窗口可能漏掉训练记录，历史覆盖仍不完整。', pollingFailed: '有 {count} 个场景刷新失败，已保留之前的成绩。', hybridNotice: '已保存 {scenarios} 个场景的 {count} 条训练记录，来源为本地 Stats 与去重后的线上成绩。缺失文件或接口窗口截断可能造成遗漏，训练时长仍不可用。',
  localHistory: '本地 Stats 历史', localNotice: '已导入 {scenarios} 个场景的 {count} 份完成训练 CSV。统计覆盖仍保留的本地文件，不含已删除文件、未保存训练和挑战外时间。不会用 Fight Time 推算训练时长。', localFetched: '本地 Stats 导入于 {date}', recordedRuns: '已记录训练次数', recordedActive30: '已记录训练日 / 最近 30 天', runsActive: '次 / 已记录训练日', recordedPeak: '训练开始最集中的时段', recordedWeekday: '最近 30 天按星期统计的已记录次数',
  partialHistory: '部分在线历史', historyRecords: '历史成绩记录', historyNotice: '已恢复 {scenarios} 个场景的 {count} 条带时间戳成绩。各场景历史条数有限，每日次数仅为下限，没有记录的日期仍是未知。训练时长不可用。', historyFetched: '历史读取于 {date}', historyTrend: '每周已确认训练次数 · 部分历史', historyFocus: '最近 30 天 · 已确认记录', historyProgress: '最近 30 天 · 最新成绩对比首条可读成绩', historyPercent: '可读成绩之间的变化，非 PB 提升', counterUnverified: '线上累计 Plays 的含义仍在核查，暂不作为终身训练次数。',
  online: '在线追踪', reportedPlays: '线上累计 Plays', observedPlays: '采样新增 Plays', knownActive: '已知训练天数', durationMissing: '无法获取训练时长', trackingSince: '追踪始于 {date}', waitingBaseline: '等待首份数据快照', updated: '更新于 {date}', onlineNotice: '活动根据 KovaaK 报告的 Plays 增量统计，并非完整 Run 日志。每日格子显示已采样的最低次数，缺失历史保持未知。目前无法获取训练时长。', focusWaiting: '取得可比较的快照并记录新增 Plays 后，这里将显示近期常练场景。', pbSubtitle: '最近上报的 PB 动态 · 非完整成绩历史', pbWaiting: '暂无公开 PB 动态。', progressMissing: '提升百分比需要成绩历史，目前不可用。', patternWaiting: '无法从这些计数推导训练时长或高峰时段。', crossDay: '有 {count} 次采样新增 Plays 跨越日界线，未计入每日格子。', sampleTrend: '每周采样新增 Plays · 每日覆盖不完整', loadError: '玩家数据加载失败。请重试或检查静态数据文件。', retry: '重试', loading: '正在加载档案…', player: '玩家', demoLink: '查看演示', partial: '记录覆盖不完整 · 次数为下限', zeroPartial: '采样区间内无新增次数，全天训练情况未知', resets: '检测到计数回退，相关区间已排除。', liveLink: '查看追踪档案', knownDays: '{count} 个已知训练日 · 部分记录', dataUnavailable: '不可用',
  language: '语言', eyebrow: '每一次练习，都留下痕迹', title: 'KovaaK 训练活动', description: '查看训练规律与成绩变化', demo: '演示档案', calendarYear: '自然年', activityYear: '活动年份', summary: '训练概览', activeDays: '训练天数', training: '训练时长', currentStreak: '当前连续天数', yearEndStreak: '年末连续天数', runs: '次', runsLabel: '训练次数', hour: '小时', minute: '分钟', minutes: '分钟',
  activity: '训练活动', activitySubtitle: '每一次练习都算数。你的 {year} 年训练记录。', metric: '热力图指标', time: '时长', noActivity: '{year} 年暂无训练记录。未知历史与已记录的零训练分别显示。', trend: '训练趋势', weeklyTime: '每周训练时长', weeklyRuns: '每周训练次数', focus: '常练场景', last30: '最近 30 个已追踪日', noScenarios: '暂无场景训练记录。', progress: '近期进步', progressSubtitle: '个人最佳成绩变化 · 最近 30 个已追踪日', noScores: '暂无成绩历史。', pattern: '训练习惯', daysWeek: '天 / 周', perActive: '/ 训练日', peak: '高峰时段', illustrative: '示例', weekdayChart: '最近 30 个已追踪日按星期统计的训练分钟数', noPattern: '积累训练记录后，这里将显示训练习惯。', footer: '进步来自练习。', mock: '模拟数据，仅供演示', asOf: '截至 {date}',
  futureDate: '未来日期', noData: '无数据', intensity: '训练量色阶', future: '未来', activePercent: '{count} 个训练日 · 占已过日期的 {percent}%', noDays: '暂无记录', noHistory: '无历史数据', timeUnavailable: '时长不可用', newPBs: '项新个人最佳', scenarios: '个场景', noTrend: '本年暂无训练数据', weeklyHours: '每周训练小时数', weekOf: '{date} 所在周', hours: '小时', scoreRange: '{name}：从 {first} 到 {last}',
};
const dictionaries = { en, zh };
interface I18n { language: Language; locale: string; setLanguage: (language: Language) => void; t: (key: keyof typeof en, values?: Record<string, string | number>) => string; weekdays: string[]; }
const Context = createContext<I18n | null>(null);
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    try { const saved = localStorage.getItem('kovaak-activity.language'); if (saved === 'en' || saved === 'zh') return saved; } catch {}
    return navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en';
  });
  useEffect(() => {
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en';
    document.title = dictionaries[language].title;
    try { localStorage.setItem('kovaak-activity.language', language); } catch {}
  }, [language]);
  const t: I18n['t'] = (key, values = {}) => dictionaries[language][key].replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
  return <Context.Provider value={{ language, locale: language === 'zh' ? 'zh-CN' : 'en-US', setLanguage, t, weekdays: language === 'zh' ? ['周一', '周二', '周三', '周四', '周五', '周六', '周日'] : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] }}>{children}</Context.Provider>;
}
export function useI18n() { const context = useContext(Context); if (!context) throw new Error('LanguageProvider is required'); return context; }
